// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmb6VsXwWebmRznU4brfK08FD0xGGs1yM',
    appId: '1:128857833317:web:71c39f74c9fd538cb9ab8c',
    messagingSenderId: '128857833317',
    projectId: 'my-app-bb803',
    authDomain: 'my-app-bb803.firebaseapp.com',
    storageBucket: 'my-app-bb803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdbHIagJowSvkWRIuzQ6JmtVCDKNH1bE',
    appId: '1:128857833317:android:4a2476104b6cbb5eb9ab8c',
    messagingSenderId: '128857833317',
    projectId: 'my-app-bb803',
    storageBucket: 'my-app-bb803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrbojjHIlJaMuVjPNzAIrik6ZXqw_yjc',
    appId: '1:128857833317:ios:5f286194cea3410fb9ab8c',
    messagingSenderId: '128857833317',
    projectId: 'my-app-bb803',
    storageBucket: 'my-app-bb803.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrbojjHIlJaMuVjPNzAIrik6ZXqw_yjc',
    appId: '1:128857833317:ios:5f286194cea3410fb9ab8c',
    messagingSenderId: '128857833317',
    projectId: 'my-app-bb803',
    storageBucket: 'my-app-bb803.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmb6VsXwWebmRznU4brfK08FD0xGGs1yM',
    appId: '1:128857833317:web:2b5171768227836fb9ab8c',
    messagingSenderId: '128857833317',
    projectId: 'my-app-bb803',
    authDomain: 'my-app-bb803.firebaseapp.com',
    storageBucket: 'my-app-bb803.firebasestorage.app',
  );
}
